var data= [
  {
    id: 1,
    nombre: "Franco Armani",
    edad: "36 años",
    numero: "1",
    posicion: "Arquero",
    equipo: "River Plate",
    image: "./img/jugadores/armani.jpg",
  },
  {
    id: 2,
    nombre: "Geronimo Rulli",
    edad: "30 años",
    numero: "12",
    posicion: "Arquero",
    equipo: "Villareal",
    image: "./img/jugadores/rulli.jpg",
  },
  {
    id: 3,
    nombre: "Emiliano Martinez",
    edad: "30 años",
    numero: "23",
    posicion: "Arquero",
    equipo: "Aston Villa",
    image: "./img/jugadores/dibu_martinez.jpg",
  },
  {
    id: 4,
    nombre: "Juan Foyth",
    edad: "24 años",
    numero: "2",
    posicion: "Defensor",
    equipo: "Villareal",
    image: "./img/jugadores/foyth.jpg",
  },
  {
    id: 5,
    nombre: "Nicolás Tagliafico",
    edad: "30 años",
    numero: "3",
    posicion: "Defensor",
    equipo: "Lyon",
    image: "./img/jugadores/tagliafico.jpg",
  },
  {
    id: 6,
    nombre: "Gonzalo Montiel",
    edad: "25 años",
    numero: "4",
    posicion: "Defensor",
    equipo: "Sevilla",
    image: "./img/jugadores/montiel.jpg",
  },
  {
    id: 7,
    nombre: "Germán Pezzella",
    edad: "31 años",
    numero: "4",
    posicion: "Defensor",
    equipo: "Real Betis",
    image: "./img/jugadores/pezzella.jpg",
  },
  {
    id: 8,
    nombre: "Marcos Acuña",
    edad: "31 años",
    numero: "8",
    posicion: "Defensor",
    equipo: "Sevilla",
    image: "./img/jugadores/acuna.jpg",
  },
  {
    id: 9,
    nombre: "Cristian Romero",
    edad: "24 años",
    numero: "13",
    posicion: "Defensor",
    equipo: "Tottenham Hotspur",
    image: "./img/jugadores/cuti_romero.jpg",
  },
  {
    id: 10,
    nombre: "Nicolás Otamendi",
    edad: "34 años",
    numero: "19",
    posicion: "Defensor",
    equipo: "Benfica",
    image: "./img/jugadores/otamendi.jpg",
  },
  {
    id: 11,
    nombre: "Lisandro Martínez",
    edad: "24 años",
    numero: "25",
    posicion: "Defensor",
    equipo: "Manchester United",
    image: "./img/jugadores/lisandro.jpg",
  },
  {
    id: 12,
    nombre: "Nahuel Molina",
    edad: "24 años",
    numero: "26",
    posicion: "Defensor",
    equipo: "Atletico de Madrid",
    image: "./img/jugadores/molina.jpg",
  },
  {
    id: 13,
    nombre: "Leandro Paredes",
    edad: "28 años",
    numero: "5",
    posicion: "Mediocampista",
    equipo: "Juventus",
    image: "./img/jugadores/paredes.jpg",
  },
  {
    id: 14,
    nombre: "Rodrigo De Paul",
    edad: "28 años",
    numero: "7",
    posicion: "Mediocampista",
    equipo: "Atletico de Madrid",
    image: "./img/jugadores/depaul.jpg",
  },
  {
    id: 15,
    nombre: "Exequiel Palacios",
    edad: "30 años",
    numero: "14",
    posicion: "Mediocampista",
    equipo: "Bayer Leverkusen",
    image: "./img/jugadores/palacios.jpg",
  },
  {
    id: 16,
    nombre: "Alejandro Gómez",
    edad: "34 años",
    numero: "17",
    posicion: "Mediocampista",
    equipo: "Sevilla",
    image: "./img/jugadores/papugomez.jpg",
  },
  {
    id: 17,
    nombre: "Guido Rodriguez",
    edad: "28 años",
    numero: "18",
    posicion: "Mediocampista",
    equipo: "Real Betis",
    image: "./img/jugadores/guido_rodriguez.jpg",
  },
  {
    id: 18,
    nombre: "Alexis Mac Allister",
    edad: "23 años",
    numero: "20",
    posicion: "Mediocampista",
    equipo: "Brighton",
    image: "./img/jugadores/macallister.jpg",
  },
  {
    id: 19,
    nombre: "Enzo Fernandez",
    edad: "21 años",
    numero: "24",
    posicion: "Mediocampista",
    equipo: "Benfica",
    image: "./img/jugadores/enzo_fernandez.jpg",
  },
  {
    id: 20,
    nombre: "Julián Alvarez",
    edad: "22 años",
    numero: "9",
    posicion: "Delantero",
    equipo: "Manchester City",
    image: "./img/jugadores/julian_alvarez.jpg",
  },
  {
    id: 21,
    nombre: "Lionel Messi (C)",
    edad: "35 años",
    numero: "10",
    posicion: "Delantero",
    equipo: "PSG",
    image: "./img/jugadores/messi.jpg",
  },
  {
    id: 22,
    nombre: "Angel Di Maria",
    edad: "34 años",
    numero: "11",
    posicion: "Delantero",
    equipo: "Juventus",
    image: "./img/jugadores/fideo.jpg",
  },
  {
    id: 23,
    nombre: "Angel Correa",
    edad: "27 años",
    numero: "15",
    posicion: "Delantero",
    equipo: "Atletico de Madrid",
    image: "./img/jugadores/angel_correa.jpg",
  },
  {
    id: 24,
    nombre: "Thiago Almada",
    edad: "21 años",
    numero: "16",
    posicion: "Delantero",
    equipo: "Atlanta United",
    image: "./img/jugadores/thiago_almada.jpg",
  },
  {
    id: 25,
    nombre: "Paulo Dybala",
    edad: "29 años",
    numero: "21",
    posicion: "Delantero",
    equipo: "Roma",
    image: "./img/jugadores/dybala.jpg",
  },
  {
    id: 26,
    nombre: "Lautaro Martinez",
    edad: "25 años",
    numero: "22",
    posicion: "Delantero",
    equipo: "Internazionale",
    image: "./img/jugadores/lautaro.jpg",
  },
  {
    id: 27,
    nombre: "Lionel Scaloni",
    edad: "44 años",
    numero: "",
    posicion: "Entrenador",
    equipo: "Seleccion Argentina",
    image: "./img/jugadores/",
  }
]
